//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Fairino
{
    [Serializable]
    public class RemoteCmdInterfaceRequest : Message
    {
        public const string k_RosMessageName = "fairino_msgs/RemoteCmdInterface";
        public override string RosMessageName => k_RosMessageName;

        public string cmd_str;

        public RemoteCmdInterfaceRequest()
        {
            this.cmd_str = "";
        }

        public RemoteCmdInterfaceRequest(string cmd_str)
        {
            this.cmd_str = cmd_str;
        }

        public static RemoteCmdInterfaceRequest Deserialize(MessageDeserializer deserializer) => new RemoteCmdInterfaceRequest(deserializer);

        private RemoteCmdInterfaceRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.cmd_str);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.cmd_str);
        }

        public override string ToString()
        {
            return "RemoteCmdInterfaceRequest: " +
            "\ncmd_str: " + cmd_str.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
