//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Fairino
{
    [Serializable]
    public class RemoteCmdInterfaceResponse : Message
    {
        public const string k_RosMessageName = "fairino_msgs/RemoteCmdInterface";
        public override string RosMessageName => k_RosMessageName;

        public string cmd_res;

        public RemoteCmdInterfaceResponse()
        {
            this.cmd_res = "";
        }

        public RemoteCmdInterfaceResponse(string cmd_res)
        {
            this.cmd_res = cmd_res;
        }

        public static RemoteCmdInterfaceResponse Deserialize(MessageDeserializer deserializer) => new RemoteCmdInterfaceResponse(deserializer);

        private RemoteCmdInterfaceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.cmd_res);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.cmd_res);
        }

        public override string ToString()
        {
            return "RemoteCmdInterfaceResponse: " +
            "\ncmd_res: " + cmd_res.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
