"""Hardware-free timing contract shared by the executor and its launcher."""

STATE_MAX_AGE_SEC = 0.25
STOP_RPC_TIMEOUT_SEC = 4.0
STOP_FEEDBACK_TIMEOUT_SEC = 3.0
EXECUTOR_SHUTDOWN_MARGIN_SEC = 5.0
LAUNCHER_INTERRUPT_GRACE_SEC = 15.0
LAUNCHER_TERMINATE_GRACE_SEC = 5.0

assert (STOP_RPC_TIMEOUT_SEC + STOP_FEEDBACK_TIMEOUT_SEC
        + EXECUTOR_SHUTDOWN_MARGIN_SEC <= LAUNCHER_INTERRUPT_GRACE_SEC)
