<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>fr5_unity_endpoint</name>
  <version>0.1.0</version>
  <description>Launch FR5 MoveIt and the Unity ROS-TCP Endpoint together.</description>
  <maintainer email="maintainer@example.com">FR5 MVP maintainer</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>fr5_moveit_mvp</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ros_tcp_endpoint</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
