BEGIN;

CREATE SCHEMA IF NOT EXISTS production;
CREATE SCHEMA IF NOT EXISTS part_catalog;
CREATE SCHEMA IF NOT EXISTS defect_report;

-- production: ROS2 assembly node owns writes.

CREATE TABLE IF NOT EXISTS production.parts (
    part_id text PRIMARY KEY,
    part_name text NOT NULL,
    part_category text NOT NULL,
    stock_quantity integer NOT NULL DEFAULT 0,
    CONSTRAINT ck_parts_stock CHECK (stock_quantity >= 0)
);

CREATE TABLE IF NOT EXISTS production.products (
    product_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code text NOT NULL,
    product_name text NOT NULL,
    product_version text NOT NULL,
    is_selectable boolean NOT NULL DEFAULT true,
    definition_locked_at timestamptz,
    CONSTRAINT uq_products_code_version UNIQUE (product_code, product_version)
);

CREATE TABLE IF NOT EXISTS production.product_slots (
    product_slot_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint NOT NULL REFERENCES production.products(product_id),
    slot_code text NOT NULL,
    part_id text NOT NULL REFERENCES production.parts(part_id),
    CONSTRAINT uq_product_slots_product_slot UNIQUE (product_id, slot_code)
);

CREATE INDEX IF NOT EXISTS ix_product_slots_part
    ON production.product_slots(part_id);

CREATE TABLE IF NOT EXISTS production.jobs (
    job_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint NOT NULL REFERENCES production.products(product_id),
    requested_quantity integer NOT NULL,
    recipe_version text NOT NULL,
    job_status text NOT NULL DEFAULT 'PENDING',
    requested_at timestamptz NOT NULL DEFAULT now(),
    job_started_at timestamptz,
    job_finished_at timestamptz,
    CONSTRAINT ck_jobs_quantity CHECK (requested_quantity > 0),
    CONSTRAINT ck_jobs_status CHECK (
        job_status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED')
    ),
    CONSTRAINT ck_jobs_dates CHECK (
        (job_started_at IS NULL OR job_started_at >= requested_at)
        AND (job_finished_at IS NULL OR job_finished_at >= requested_at)
        AND (job_started_at IS NULL OR job_finished_at IS NULL
             OR job_finished_at >= job_started_at)
    )
);

CREATE INDEX IF NOT EXISTS ix_jobs_product_status
    ON production.jobs(product_id, job_status);
CREATE INDEX IF NOT EXISTS ix_jobs_requested_at
    ON production.jobs(requested_at);
CREATE INDEX IF NOT EXISTS ix_jobs_product_recipe
    ON production.jobs(product_id, recipe_version);

-- MVP contract: one PENDING or RUNNING job at a time.
CREATE UNIQUE INDEX IF NOT EXISTS uq_jobs_single_active
    ON production.jobs ((1))
    WHERE job_status IN ('PENDING', 'RUNNING');

CREATE TABLE IF NOT EXISTS production.units (
    unit_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id bigint NOT NULL REFERENCES production.jobs(job_id),
    unit_sequence_in_job integer NOT NULL,
    unit_status text NOT NULL DEFAULT 'RUNNING',
    inspection_result text NOT NULL DEFAULT 'PENDING',
    inspection_image_path text,
    assembly_started_at timestamptz NOT NULL DEFAULT now(),
    assembly_completed_at timestamptz,
    inspected_at timestamptz,
    CONSTRAINT uq_units_job_sequence UNIQUE (job_id, unit_sequence_in_job),
    CONSTRAINT ck_units_sequence CHECK (unit_sequence_in_job > 0),
    CONSTRAINT ck_units_status CHECK (
        unit_status IN ('RUNNING', 'COMPLETED', 'FAILED')
    ),
    CONSTRAINT ck_units_inspection CHECK (
        inspection_result IN ('PENDING', 'PASS', 'FAIL')
    ),
    CONSTRAINT ck_units_inspected CHECK (
        (inspection_result = 'PENDING' AND inspected_at IS NULL)
        OR
        (inspection_result IN ('PASS', 'FAIL')
         AND unit_status = 'COMPLETED'
         AND assembly_completed_at IS NOT NULL
         AND inspected_at IS NOT NULL)
    ),
    CONSTRAINT ck_units_dates CHECK (
        (assembly_completed_at IS NULL
         OR assembly_completed_at >= assembly_started_at)
        AND (inspected_at IS NULL OR assembly_completed_at IS NOT NULL)
        AND (inspected_at IS NULL OR inspected_at >= assembly_completed_at)
    )
);

CREATE INDEX IF NOT EXISTS ix_units_inspected_at
    ON production.units(inspected_at);

CREATE TABLE IF NOT EXISTS production.unit_defects (
    unit_defect_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_id bigint NOT NULL REFERENCES production.units(unit_id),
    product_slot_id bigint NOT NULL
        REFERENCES production.product_slots(product_slot_id),
    defect_type text NOT NULL,
    CONSTRAINT uq_unit_defects_unit_slot UNIQUE (unit_id, product_slot_id),
    CONSTRAINT ck_unit_defects_type CHECK (
        defect_type IN ('MISSING', 'POSITION_ERROR', 'ORIENTATION_ERROR', 'CRACK')
    )
);

CREATE INDEX IF NOT EXISTS ix_unit_defects_product_slot
    ON production.unit_defects(product_slot_id);

-- part_catalog: datasheet loader owns writes.

CREATE TABLE IF NOT EXISTS part_catalog.datasheet_loads (
    load_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_file text NOT NULL,
    source_dated_on date NOT NULL,
    loaded_at timestamptz NOT NULL DEFAULT now(),
    row_counts jsonb NOT NULL DEFAULT '{}'::jsonb,
    load_status text NOT NULL,
    CONSTRAINT ck_datasheet_loads_row_counts CHECK (
        jsonb_typeof(row_counts) = 'object'
    ),
    CONSTRAINT ck_datasheet_loads_status CHECK (
        load_status IN ('SUCCEEDED', 'FAILED')
    )
);

CREATE TABLE IF NOT EXISTS part_catalog.sources (
    source_id text PRIMARY KEY,
    source_type text NOT NULL,
    item_name text NOT NULL,
    verified_content text NOT NULL,
    url text,
    checked_at date NOT NULL,
    load_id bigint NOT NULL REFERENCES part_catalog.datasheet_loads(load_id),
    CONSTRAINT ck_sources_type CHECK (
        source_type IN ('PRIMARY', 'ALTERNATE')
    )
);

CREATE TABLE IF NOT EXISTS part_catalog.part_groups (
    group_id text PRIMARY KEY,
    category_label text NOT NULL,
    role_summary text NOT NULL,
    load_id bigint NOT NULL REFERENCES part_catalog.datasheet_loads(load_id)
);

CREATE TABLE IF NOT EXISTS part_catalog.part_candidates (
    candidate_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id text NOT NULL REFERENCES part_catalog.part_groups(group_id),
    candidate_role text NOT NULL,
    alternate_code text,
    manufacturer text NOT NULL,
    manufacturer_part_number text NOT NULL,
    key_spec text,
    lifecycle_status text,
    compatibility_status text,
    revalidation_items text,
    source_id text REFERENCES part_catalog.sources(source_id),
    note text,
    load_id bigint NOT NULL REFERENCES part_catalog.datasheet_loads(load_id),
    CONSTRAINT uq_part_candidates_group_mpn
        UNIQUE (group_id, manufacturer_part_number),
    CONSTRAINT ck_part_candidates_role CHECK (
        candidate_role IN ('PRIMARY', 'ALTERNATE')
    ),
    CONSTRAINT ck_part_candidates_alternate_code CHECK (
        (candidate_role = 'PRIMARY' AND alternate_code IS NULL)
        OR (candidate_role = 'ALTERNATE' AND alternate_code IS NOT NULL)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_part_candidates_one_primary
    ON part_catalog.part_candidates(group_id)
    WHERE candidate_role = 'PRIMARY';

CREATE TABLE IF NOT EXISTS part_catalog.part_supply (
    supply_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id bigint NOT NULL
        REFERENCES part_catalog.part_candidates(candidate_id),
    supplier text NOT NULL,
    supplier_part_number text,
    unit_price numeric(18, 4),
    currency text,
    price_quantity_basis integer,
    moq integer,
    stock_status text,
    lead_time text,
    price_checked_at date,
    load_id bigint NOT NULL REFERENCES part_catalog.datasheet_loads(load_id),
    CONSTRAINT ck_part_supply_price CHECK (
        unit_price IS NULL OR unit_price >= 0
    ),
    CONSTRAINT ck_part_supply_currency CHECK (
        currency IS NULL OR char_length(currency) = 3
    ),
    CONSTRAINT ck_part_supply_price_basis CHECK (
        price_quantity_basis IS NULL OR price_quantity_basis > 0
    ),
    CONSTRAINT ck_part_supply_moq CHECK (moq IS NULL OR moq > 0)
);

CREATE INDEX IF NOT EXISTS ix_part_supply_candidate
    ON part_catalog.part_supply(candidate_id);

CREATE TABLE IF NOT EXISTS part_catalog.quality_checklists (
    checklist_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category text NOT NULL,
    incoming_inspection text,
    assembly_control text,
    reliability_test text,
    action_on_anomaly text,
    load_id bigint NOT NULL REFERENCES part_catalog.datasheet_loads(load_id)
);

CREATE INDEX IF NOT EXISTS ix_quality_checklists_category
    ON part_catalog.quality_checklists(category);

-- defect_report: quality scanner/report backend owns writes.

CREATE TABLE IF NOT EXISTS defect_report.thresholds (
    threshold_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_id text,
    defect_type text,
    threshold_rate numeric(10, 8) NOT NULL,
    min_inspected_quantity integer NOT NULL,
    window_days integer NOT NULL,
    evaluation_mode text NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    effective_from timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_thresholds_defect_type CHECK (
        defect_type IS NULL OR defect_type IN (
            'MISSING', 'POSITION_ERROR', 'ORIENTATION_ERROR', 'CRACK'
        )
    ),
    CONSTRAINT ck_thresholds_rate CHECK (
        threshold_rate >= 0 AND threshold_rate <= 1
    ),
    CONSTRAINT ck_thresholds_min_quantity CHECK (min_inspected_quantity > 0),
    CONSTRAINT ck_thresholds_window CHECK (window_days > 0),
    CONSTRAINT ck_thresholds_mode CHECK (
        evaluation_mode IN ('ROLLING', 'QUARTERLY')
    )
);

CREATE INDEX IF NOT EXISTS ix_thresholds_active_mode
    ON defect_report.thresholds(evaluation_mode, effective_from DESC)
    WHERE is_active;

CREATE TABLE IF NOT EXISTS defect_report.alerts (
    alert_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_code text NOT NULL UNIQUE,
    trigger_type text NOT NULL,
    part_id text NOT NULL,
    defect_type text NOT NULL,
    threshold_id bigint NOT NULL
        REFERENCES defect_report.thresholds(threshold_id),
    period_start timestamptz NOT NULL,
    period_end timestamptz NOT NULL,
    inspected_quantity integer NOT NULL,
    inspected_unit_quantity integer NOT NULL,
    defective_quantity integer NOT NULL,
    defect_rate numeric(10, 8) NOT NULL,
    threshold_rate numeric(10, 8) NOT NULL,
    min_inspected_quantity integer NOT NULL,
    first_exceeded_at timestamptz,
    source_recipe_version text NOT NULL,
    alert_status text NOT NULL DEFAULT 'ISSUED',
    assignee text,
    issued_at timestamptz NOT NULL DEFAULT now(),
    initial_action_due_at timestamptz,
    final_action_due_at timestamptz,
    closed_at timestamptz,
    document_path text,
    CONSTRAINT ck_alerts_trigger CHECK (
        trigger_type IN ('THRESHOLD', 'QUARTERLY')
    ),
    CONSTRAINT ck_alerts_defect_type CHECK (
        defect_type IN ('MISSING', 'POSITION_ERROR', 'ORIENTATION_ERROR', 'CRACK')
    ),
    CONSTRAINT ck_alerts_status CHECK (
        alert_status IN ('ISSUED', 'ASSIGNED', 'IN_PROGRESS', 'VERIFYING', 'CLOSED')
    ),
    CONSTRAINT ck_alerts_period CHECK (period_end > period_start),
    CONSTRAINT ck_alerts_counts CHECK (
        inspected_quantity > 0
        AND inspected_unit_quantity > 0
        AND defective_quantity >= 0
        AND defective_quantity <= inspected_quantity
        AND min_inspected_quantity > 0
    ),
    CONSTRAINT ck_alerts_rates CHECK (
        defect_rate >= 0 AND defect_rate <= 1
        AND threshold_rate >= 0 AND threshold_rate <= 1
    ),
    CONSTRAINT ck_alerts_closed CHECK (
        (alert_status = 'CLOSED' AND closed_at IS NOT NULL)
        OR (alert_status <> 'CLOSED' AND closed_at IS NULL)
    ),
    CONSTRAINT ck_alerts_due_dates CHECK (
        initial_action_due_at IS NULL OR final_action_due_at IS NULL
        OR final_action_due_at >= initial_action_due_at
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_alerts_one_open_per_part_type
    ON defect_report.alerts(part_id, defect_type)
    WHERE alert_status <> 'CLOSED';
CREATE INDEX IF NOT EXISTS ix_alerts_status_issued
    ON defect_report.alerts(alert_status, issued_at DESC);

CREATE TABLE IF NOT EXISTS defect_report.alert_evidence (
    evidence_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id bigint NOT NULL REFERENCES defect_report.alerts(alert_id),
    unit_id bigint NOT NULL,
    product_slot_id bigint NOT NULL,
    slot_code text NOT NULL,
    defect_type text NOT NULL,
    inspected_at timestamptz NOT NULL,
    inspection_image_path text,
    CONSTRAINT uq_alert_evidence_alert_unit_slot
        UNIQUE (alert_id, unit_id, product_slot_id),
    CONSTRAINT ck_alert_evidence_defect_type CHECK (
        defect_type IN ('MISSING', 'POSITION_ERROR', 'ORIENTATION_ERROR', 'CRACK')
    )
);

CREATE INDEX IF NOT EXISTS ix_alert_evidence_unit
    ON defect_report.alert_evidence(unit_id);

CREATE TABLE IF NOT EXISTS defect_report.alert_countermeasures (
    countermeasure_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id bigint NOT NULL UNIQUE REFERENCES defect_report.alerts(alert_id),
    root_cause_summary text,
    applied_recipe_version text,
    applied_at timestamptz,
    verification_status text NOT NULL DEFAULT 'PENDING',
    verified_inspected_quantity integer,
    verified_defective_quantity integer,
    verified_defect_rate numeric(10, 8),
    verified_at timestamptz,
    CONSTRAINT ck_countermeasures_applied CHECK (
        (applied_recipe_version IS NULL AND applied_at IS NULL)
        OR (applied_recipe_version IS NOT NULL AND applied_at IS NOT NULL)
    ),
    CONSTRAINT ck_countermeasures_status CHECK (
        verification_status IN ('PENDING', 'EFFECTIVE', 'INEFFECTIVE')
    ),
    CONSTRAINT ck_countermeasures_counts CHECK (
        verified_inspected_quantity IS NULL
        OR (verified_inspected_quantity > 0
            AND verified_defective_quantity IS NOT NULL
            AND verified_defective_quantity >= 0
            AND verified_defective_quantity <= verified_inspected_quantity)
    ),
    CONSTRAINT ck_countermeasures_rate CHECK (
        verified_defect_rate IS NULL
        OR (verified_defect_rate >= 0 AND verified_defect_rate <= 1)
    ),
    CONSTRAINT ck_countermeasures_verified CHECK (
        verification_status = 'PENDING'
        OR (verified_inspected_quantity IS NOT NULL
            AND verified_defective_quantity IS NOT NULL
            AND verified_defect_rate IS NOT NULL
            AND verified_at IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS defect_report.scan_runs (
    run_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluation_mode text NOT NULL,
    window_start timestamptz NOT NULL,
    window_end timestamptz NOT NULL,
    max_recorded_at timestamptz,
    scan_started_at timestamptz NOT NULL DEFAULT now(),
    scan_finished_at timestamptz,
    alerts_issued integer NOT NULL DEFAULT 0,
    run_status text NOT NULL DEFAULT 'RUNNING',
    CONSTRAINT ck_scan_runs_mode CHECK (
        evaluation_mode IN ('ROLLING', 'QUARTERLY')
    ),
    CONSTRAINT ck_scan_runs_window CHECK (window_end > window_start),
    CONSTRAINT ck_scan_runs_alerts CHECK (alerts_issued >= 0),
    CONSTRAINT ck_scan_runs_status CHECK (
        run_status IN ('RUNNING', 'SUCCEEDED', 'FAILED')
    ),
    CONSTRAINT ck_scan_runs_finished CHECK (
        (run_status = 'RUNNING' AND scan_finished_at IS NULL)
        OR (run_status IN ('SUCCEEDED', 'FAILED') AND scan_finished_at IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS ix_scan_runs_mode_status
    ON defect_report.scan_runs(evaluation_mode, run_status, window_end DESC);

COMMIT;
